### ISSUE TITLE
Should trains/obstacles self-generate

### ISSUE THREAD

**Issue by nadeemabdulhamid** [berry-cs/csc121-project-nathan-jeanmarc#1]
Instead of keyboard controls (which are ok for debugging), make objects on the track generate and appear (randomly?) automatically.

**Comment by jmwages** [comment]
Added a spawner class that handles all spawning of trains and barriers. All obstacles on the screen are spawned based on spawn thresholds defined in constants. Works functionally but needs tweaking to get spawn rate how we want it
